from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "shared" / "protocol"))

from parol6_protocol import Frame, MessageType, encode_body, encode_tcp, encode_uart


def main() -> None:
    schema_path = ROOT / "config" / "protocol.yaml"
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    frames = [
        Frame(message_type=MessageType.HEARTBEAT),
        Frame(
            message_type=MessageType.HELLO,
            flags=0xA5,
            payload=b"PAROL6\x00MATTJ",
            session_id=0x11223344,
            sequence=0x01020304,
            acknowledgement=0x05060708,
            sender_time_us=0x0102030405060708,
        ),
        Frame(
            message_type=MessageType.TRAJECTORY_COMMIT,
            payload=(0x0123456789ABCDEF).to_bytes(8, "little"),
            session_id=7,
            sequence=99,
            acknowledgement=98,
            sender_time_us=1_000_000,
        ),
    ]
    vectors = {
        "schema": "protocol_v1",
        "protocol": schema["protocol"],
        "vectors": [
            {
                "name": f"vector_{index}_{MessageType(frame.message_type).name.lower()}",
                "fields": {
                    "version": frame.version,
                    "message_type": frame.message_type,
                    "flags": frame.flags,
                    "payload_hex": frame.payload.hex(),
                    "session_id": frame.session_id,
                    "sequence": frame.sequence,
                    "acknowledgement": frame.acknowledgement,
                    "sender_time_us": frame.sender_time_us,
                },
                "body_hex": encode_body(frame).hex(),
                "uart_hex": encode_uart(frame).hex(),
                "tcp_hex": encode_tcp(frame).hex(),
            }
            for index, frame in enumerate(frames)
        ],
    }
    output = ROOT / "shared" / "test_vectors" / "protocol_v1.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(vectors, indent=2) + "\n", encoding="utf-8")

    header = render_cpp_header(schema)
    header_path = ROOT / "shared" / "generated" / "protocol_v1.hpp"
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(header, encoding="utf-8")


def render_cpp_header(schema: dict[str, object]) -> str:
    messages = schema["messages"]
    states = schema["states"]
    errors = schema["errors"]
    flags = schema["flags"]
    payloads = schema["payloads"]
    assert isinstance(messages, dict) and isinstance(states, dict) and isinstance(errors, dict)
    assert isinstance(flags, dict) and isinstance(payloads, dict)

    def enum_lines(values: dict[str, int]) -> str:
        return "\n".join(f"  {name} = {value}," for name, value in values.items())

    return f"""// Generated by tools/protocol_analyzer/generate_vectors.py. Do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace parol6::protocol {{
inline constexpr std::uint8_t kProtocolMajor = {schema['protocol']['major']};
inline constexpr std::uint8_t kProtocolMinor = {schema['protocol']['minor']};
inline constexpr std::size_t kMaxPayloadBytes = {schema['framing']['max_payload_bytes']};
inline constexpr std::size_t kReplayWindow = {schema['framing']['replay_window']};
inline constexpr std::size_t kHeartbeatReplyPayloadBytes = {payloads['HEARTBEAT_REPLY']['size']};
inline constexpr std::size_t kDeviceInfoPayloadBytes = {payloads['DEVICE_INFO']['size']};
inline constexpr std::size_t kNackPayloadBytes = {payloads['NACK']['size']};

enum class FrameFlag : std::uint8_t {{
{enum_lines(flags)}
}};

enum class MessageType : std::uint8_t {{
{enum_lines(messages)}
}};

enum class ControllerState : std::uint8_t {{
{enum_lines(states)}
}};

enum class ErrorCode : std::uint8_t {{
{enum_lines(errors)}
}};
}}  // namespace parol6::protocol
"""


if __name__ == "__main__":
    main()
