"use client";

import { useCallback, useEffect, useRef, useState, useSyncExternalStore } from "react";

type SerialPortLike = { readable: ReadableStream<Uint8Array> | null; writable: WritableStream<Uint8Array> | null; open(options: { baudRate: number }): Promise<void>; close(): Promise<void> };
type SerialManager = { requestPort(options?: { filters?: { usbVendorId?: number; usbProductId?: number }[] }): Promise<SerialPortLike> };
type RawDirection = "+" | "-";
type ActiveLevel = "ACTIVE_HIGH" | "ACTIVE_LOW";
type JointDraft = { homeRaw: RawDirection; positiveRaw: RawDirection; active: ActiveLevel };
type JointCalibration = { configured: boolean; homeRaw: RawDirection; positiveRaw: RawDirection; negativeRaw: RawDirection; active: "HIGH" | "LOW"; minSet: boolean; minMdeg: number; maxSet: boolean; maxMdeg: number; pulsesPerDegree: number };
type CalibrationHeader = { schema: number; storage: string; sequence: number; deviceUid: string };
type SensorValue = { raw: number; stable?: number };

const joints = [
  { id: "J1", name: "Base", slot: "MOTOR0", driver: "Servo42C", servo: true, pulsesPerDegree: 114 },
  { id: "J2", name: "Shoulder", slot: "MOTOR1", driver: "Servo42C", servo: true, pulsesPerDegree: 356 },
  { id: "J3", name: "Upper arm", slot: "MOTOR2", driver: "TMC2209", servo: false, pulsesPerDegree: 161 },
  { id: "J4", name: "Elbow", slot: "MOTOR3", driver: "TMC2209", servo: false, pulsesPerDegree: 36 },
  { id: "J5", name: "Wrist pitch", slot: "MOTOR4", driver: "TMC2209", servo: false, pulsesPerDegree: 36 },
  { id: "J6", name: "Wrist rotate", slot: "MOTOR5", driver: "TMC2209", servo: false, pulsesPerDegree: 89 },
] as const;

const defaults: Record<string, JointDraft> = {
  J1: { homeRaw: "-", positiveRaw: "+", active: "ACTIVE_LOW" }, J2: { homeRaw: "-", positiveRaw: "+", active: "ACTIVE_HIGH" },
  J3: { homeRaw: "-", positiveRaw: "+", active: "ACTIVE_HIGH" }, J4: { homeRaw: "+", positiveRaw: "+", active: "ACTIVE_LOW" },
  J5: { homeRaw: "-", positiveRaw: "+", active: "ACTIVE_HIGH" }, J6: { homeRaw: "-", positiveRaw: "+", active: "ACTIVE_LOW" },
};
const firmwareVersions = new Set(["0.8.0-calibration-rc", "0.8.1-calibration-rc"]);
const homeOrder = ["J1", "J2", "J3", "J4", "J6", "J5"];

function crc32c(text: string) {
  let crc = 0xffffffff;
  for (const byte of new TextEncoder().encode(text)) { crc ^= byte; for (let bit = 0; bit < 8; bit += 1) crc = (crc >>> 1) ^ ((crc & 1) ? 0x82f63b78 : 0); }
  return ((crc ^ 0xffffffff) >>> 0).toString(16).toUpperCase().padStart(8, "0");
}

export default function CommissioningPanel({ onShowWiring }: { onShowWiring: () => void }) {
  const portRef = useRef<SerialPortLike | null>(null);
  const readerRef = useRef<ReadableStreamDefaultReader<Uint8Array> | null>(null);
  const writerRef = useRef<WritableStreamDefaultWriter<Uint8Array> | null>(null);
  const bufferRef = useRef(""); const tokenRef = useRef("");
  const sendRef = useRef<(command: string) => Promise<void>>(async () => undefined);
  const servoQueueRef = useRef<string[]>([]); const homeQueueRef = useRef<string[]>([]);
  const holdKeepaliveRef = useRef<number | null>(null); const holdingRef = useRef<string | null>(null);

  const [connected, setConnected] = useState(false); const [firmware, setFirmware] = useState("Not identified");
  const [message, setMessage] = useState("Connect the Octopus. Nothing moves automatically."); const [, setToken] = useState("");
  const [selectedJoint, setSelectedJoint] = useState("J1"); const [motionEnabled, setMotionEnabled] = useState(false);
  const [motionEnablePending, setMotionEnablePending] = useState(false); const [moving, setMoving] = useState(false);
  const [, setActiveJoint] = useState("NONE"); const [motorHeld, setMotorHeld] = useState<string | null>(null);
  const [holding, setHolding] = useState<string | null>(null); const [servoGates, setServoGates] = useState<Record<string, boolean>>({ J1: false, J2: false });
  const [positions, setPositions] = useState<Record<string, number>>({}); const [homed, setHomed] = useState<Record<string, boolean>>({});
  const [sensors, setSensors] = useState<Record<string, SensorValue>>({}); const [calibrations, setCalibrations] = useState<Record<string, JointCalibration>>({});
  const [drafts, setDrafts] = useState<Record<string, JointDraft>>(defaults); const [header, setHeader] = useState<CalibrationHeader | null>(null);
  const [jogIncrement, setJogIncrement] = useState(1000); const [holdSpeed, setHoldSpeed] = useState(6000); const [logs, setLogs] = useState<string[]>([]);

  const serialSupported = useSyncExternalStore(() => () => undefined, () => "serial" in navigator, () => true);
  const firmwareReady = firmwareVersions.has(firmware); const rawDiscoveryReady = firmware === "0.8.1-calibration-rc";
  const joint = joints.find((item) => item.id === selectedJoint) ?? joints[0]; const saved = calibrations[selectedJoint];
  const draft = drafts[selectedJoint] ?? defaults[selectedJoint]; const angleMdeg = positions[selectedJoint] ?? 0; const sensor = sensors[selectedJoint];
  const completeCount = joints.filter(({ id }) => calibrations[id]?.configured && calibrations[id]?.minSet && calibrations[id]?.maxSet).length;
  const calibrationComplete = completeCount === joints.length; const allHomed = joints.every(({ id }) => homed[id]); const busy = moving || motionEnablePending;

  const appendLog = useCallback((line: string) => setLogs((current) => [...current.slice(-79), line]), []);
  const clearHold = useCallback(() => { if (holdKeepaliveRef.current !== null) window.clearInterval(holdKeepaliveRef.current); holdKeepaliveRef.current = null; holdingRef.current = null; setHolding(null); }, []);
  const send = useCallback(async (command: string) => { if (!writerRef.current) throw new Error("Serial connection is not open"); appendLog(`> ${command}`); await writerRef.current.write(new TextEncoder().encode(`${command}\n`)); }, [appendLog]);
  useEffect(() => { sendRef.current = send; }, [send]);

  const sendNextHome = useCallback((nextToken: string) => { const next = homeQueueRef.current.shift(); if (!next) { setMessage("Home All complete. Every joint is referenced at 0°."); return; } window.setTimeout(() => void sendRef.current(`HOME ${next} ${nextToken} START`), 160); }, []);

  const parseLine = useCallback((line: string) => {
    appendLog(line); const nextToken = line.match(/\btoken=([0-9A-F]{8})\b/)?.[1]; if (nextToken) { tokenRef.current = nextToken; setToken(nextToken); }
    if (line.startsWith("PAROL6_MOTION_RC_READY")) { const version = line.match(/\bversion=([^ ]+)/)?.[1] ?? "Unknown"; setFirmware(version); setMessage(firmwareVersions.has(version) ? "Controller ready. Enable setup motion when you are physically ready." : `Unsupported firmware: ${version}`); if (firmwareVersions.has(version)) window.setTimeout(() => void sendRef.current("CALIBRATION"), 100); return; }
    if (line.startsWith("PAROL6_CALIBRATION_HEADER")) { setHeader({ schema: Number(line.match(/\bschema=([0-9]+)/)?.[1] ?? 0), storage: line.match(/\bstorage=([^ ]+)/)?.[1] ?? "UNKNOWN", sequence: Number(line.match(/\bsequence=([0-9]+)/)?.[1] ?? 0), deviceUid: line.match(/\bdevice_uid=([0-9A-F]+)/)?.[1] ?? "UNKNOWN" }); return; }
    if (line.startsWith("PAROL6_CALIBRATION joint=")) {
      const id = line.match(/\bjoint=(J[1-6])/)?.[1]; if (!id) return; const configured = /\bconfigured=1\b/.test(line);
      const value: JointCalibration = { configured, homeRaw: (line.match(/\bhome_raw=([+-])/)?.[1] ?? "-") as RawDirection, positiveRaw: (line.match(/\bpositive_raw=([+-])/)?.[1] ?? "+") as RawDirection, negativeRaw: (line.match(/\bnegative_raw=([+-])/)?.[1] ?? "-") as RawDirection, active: (line.match(/\bactive=(HIGH|LOW)/)?.[1] ?? "LOW") as "HIGH" | "LOW", minSet: /\bmin_set=1\b/.test(line), minMdeg: Number(line.match(/\bmin_mdeg=(-?[0-9]+)/)?.[1] ?? 0), maxSet: /\bmax_set=1\b/.test(line), maxMdeg: Number(line.match(/\bmax_mdeg=(-?[0-9]+)/)?.[1] ?? 0), pulsesPerDegree: Number(line.match(/\bpulses_per_degree=([0-9]+)/)?.[1] ?? 0) };
      setCalibrations((current) => ({ ...current, [id]: value })); setDrafts((current) => ({ ...current, [id]: configured ? { homeRaw: value.homeRaw, positiveRaw: value.positiveRaw, active: value.active === "HIGH" ? "ACTIVE_HIGH" : "ACTIVE_LOW" } : defaults[id] })); return;
    }
    if (line.startsWith("PAROL6_CALIBRATION_DONE")) { setMessage("Settings loaded. Select a joint and work left to right."); return; }
    if (line.startsWith("PAROL6_SENSORS")) { const next: Record<string, SensorValue> = {}; for (const match of line.matchAll(/\b(J[1-6])=([0-9]+)(?:\/([01]))?/g)) next[match[1]] = { raw: Number(match[2]), stable: match[3] === undefined ? undefined : Number(match[3]) }; setSensors(next); return; }
    if (line.startsWith("PAROL6_STATUS")) { setMoving(/\bmoving=1\b/.test(line)); setActiveJoint(line.match(/\bactive=(J[1-6]|NONE)/)?.[1] ?? "NONE"); const held = line.match(/\bheld=(J[1-6]|NONE)/)?.[1] ?? "NONE"; setMotorHeld(held === "NONE" ? null : held); const nextPositions: Record<string, number> = {}; const nextHomed: Record<string, boolean> = {}; for (const match of line.matchAll(/\b(J[1-6])_mdeg=(-?[0-9]+)/g)) nextPositions[match[1]] = Number(match[2]); for (const match of line.matchAll(/\b(J[1-6])_homed=([01])/g)) nextHomed[match[1]] = match[2] === "1"; setPositions(nextPositions); setHomed(nextHomed); return; }
    if (line.startsWith("PAROL6_SERVO_CONFIGURED")) { const id = line.match(/\bjoint=(J[12])/)?.[1]; if (id) setServoGates((current) => ({ ...current, [id]: true })); const next = servoQueueRef.current.shift(); if (next && nextToken) window.setTimeout(() => void sendRef.current(`SERVO_CONFIG ${next} ${nextToken} ACTIVE_LOW INTERFACE_VERIFIED`), 120); else { setMotionEnablePending(false); setMotionEnabled(true); setMessage("Setup motion enabled. Raw direction tests are ready."); } return; }
    if (line.startsWith("PAROL6_RAW_JOG_STARTED") || line.startsWith("PAROL6_MOTION_STARTED") || line.startsWith("PAROL6_HOME_STARTED")) { setMoving(true); setMotorHeld(null); setActiveJoint(line.match(/\bjoint=(J[1-6])/)?.[1] ?? "NONE"); setMessage(line.startsWith("PAROL6_RAW") ? "Moving 2° in raw motor direction." : line.startsWith("PAROL6_HOME") ? "Homing—slow latch becomes 0°." : "Jogging."); return; }
    if (line.startsWith("PAROL6_HOLD_STARTED")) { const id = line.match(/\bjoint=(J[1-6])/)?.[1] ?? selectedJoint; setMoving(true); setMotorHeld(null); setActiveJoint(id); setHolding(id); holdingRef.current = id; if (nextToken) holdKeepaliveRef.current = window.setInterval(() => void sendRef.current(`HOLD_KEEPALIVE ${nextToken}`), 150); setMessage(`${id} moving while held. Release to stop and hold position.`); return; }
    if (line.startsWith("PAROL6_MOTOR_HOLD joint=")) { const id = line.match(/\bjoint=(J[1-6])/)?.[1] ?? selectedJoint; clearHold(); setMoving(false); setMotorHeld(id); setActiveJoint(id); setMessage(`${id} stopped and is holding position.`); return; }
    if (line.startsWith("PAROL6_MOTOR_HOLD_RELEASED")) { setMotorHeld(null); setMoving(false); setActiveJoint("NONE"); setMessage("Holding torque released."); return; }
    if (line.startsWith("PAROL6_MOTION_DONE")) { const result = line.match(/\bresult=([^ ]+)/)?.[1] ?? "unknown"; clearHold(); setMoving(false); setMotorHeld(null); setActiveJoint("NONE"); setMessage(result === "complete" ? "Move complete." : `Motion stopped: ${result.replaceAll("_", " ")}.`); return; }
    if (line.startsWith("PAROL6_HOME joint=")) { const id = line.match(/\bjoint=(J[1-6])/)?.[1]; const result = line.match(/\bresult=([^ ]+)/)?.[1] ?? "unknown"; setMoving(false); setActiveJoint("NONE"); if (result === "complete" && id) setHomed((current) => ({ ...current, [id]: true })); if (result === "complete" && homeQueueRef.current.length && nextToken) sendNextHome(nextToken); else { if (result !== "complete") homeQueueRef.current = []; setMessage(result === "complete" ? `${id} homed at 0.000°.` : `${id} home stopped: ${result.replaceAll("_", " ")}.`); } return; }
    if (line.startsWith("PAROL6_CALIBRATION_SAVED")) { const sequence = Number(line.match(/\bsequence=([0-9]+)/)?.[1] ?? 0); setHeader((current) => current ? { ...current, sequence, storage: "FLASH" } : current); setHomed((current) => ({ ...current, [line.match(/\bjoint=(J[1-6])/)?.[1] ?? selectedJoint]: false })); setMessage("Direction setup saved. Home this joint next."); return; }
    if (line.startsWith("PAROL6_LIMIT_SAVED")) { const sequence = Number(line.match(/\bsequence=([0-9]+)/)?.[1] ?? 0); setHeader((current) => current ? { ...current, sequence, storage: "FLASH" } : current); setMessage("Limit saved and enforced by firmware."); return; }
    if (line.startsWith("PAROL6_CALIBRATION_RESET")) { const sequence = Number(line.match(/\bsequence=([0-9]+)/)?.[1] ?? 0); setHeader((current) => current ? { ...current, sequence, storage: "FLASH" } : current); setMessage("Joint setup reset."); return; }
    if (line.startsWith("PAROL6_STOPPED")) { homeQueueRef.current = []; servoQueueRef.current = []; clearHold(); setMoving(false); setMotorHeld(null); setActiveJoint("NONE"); setMotionEnabled(false); setMotionEnablePending(false); setMessage("Stopped. Drivers are disabled."); return; }
    if (line.startsWith("PAROL6_ERROR")) { const code = line.match(/\bcode=([^ ]+)/)?.[1] ?? "unknown"; homeQueueRef.current = []; clearHold(); setMoving(false); setMotorHeld(null); setActiveJoint("NONE"); setMotionEnablePending(false); setMessage(`Request blocked: ${code.replaceAll("_", " ")}.`); }
  }, [appendLog, clearHold, selectedJoint, sendNextHome]);

  const readLoop = useCallback(async (port: SerialPortLike) => { if (!port.readable) return; const reader = port.readable.getReader(); readerRef.current = reader; const decoder = new TextDecoder(); try { while (true) { const { value, done } = await reader.read(); if (done) break; bufferRef.current += decoder.decode(value, { stream: true }); const lines = bufferRef.current.split(/\r?\n/); bufferRef.current = lines.pop() ?? ""; for (const line of lines) if (line.trim()) parseLine(line.trim()); } } catch (error) { if (portRef.current) setMessage(`Connection stopped: ${error instanceof Error ? error.message : "unknown error"}`); } finally { reader.releaseLock(); if (readerRef.current === reader) readerRef.current = null; } }, [parseLine]);

  const connect = async () => { try { const manager = (navigator as Navigator & { serial?: SerialManager }).serial; if (!manager) throw new Error("Use current Chrome or Edge for USB control."); const port = await manager.requestPort({ filters: [{ usbVendorId: 0x0483, usbProductId: 0x5740 }] }); await port.open({ baudRate: 3000000 }); if (!port.writable) throw new Error("Serial port is not writable"); portRef.current = port; writerRef.current = port.writable.getWriter(); setConnected(true); setMessage("Identifying controller…"); void readLoop(port); window.setTimeout(() => void send("IDENTIFY"), 350); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not connect"); } };
  const disconnect = useCallback(async () => { try { await writerRef.current?.write(new TextEncoder().encode("STOP\n")); } catch { /* gone */ } const reader = readerRef.current; const writer = writerRef.current; const port = portRef.current; portRef.current = null; try { await reader?.cancel(); } catch { /* closed */ } try { writer?.releaseLock(); } catch { /* closed */ } writerRef.current = null; try { await port?.close(); } catch { /* gone */ } clearHold(); setConnected(false); setFirmware("Not identified"); setToken(""); tokenRef.current = ""; setMotionEnabled(false); setMotionEnablePending(false); setMoving(false); setMotorHeld(null); setServoGates({ J1: false, J2: false }); setPositions({}); setHomed({}); setSensors({}); setCalibrations({}); setHeader(null); setMessage("Disconnected. STOP was sent first."); }, [clearHold]);
  useEffect(() => () => { void disconnect(); }, [disconnect]);
  useEffect(() => { if (!connected || !firmwareReady) return; let flip = false; const timer = window.setInterval(() => { flip = !flip; void send(moving ? "PING" : flip ? "STATUS" : "SENSORS").catch(() => undefined); }, 450); return () => window.clearInterval(timer); }, [connected, firmwareReady, moving, send]);

  const enableMotion = async () => { if (motionEnabled) { await send("STOP"); setMotionEnabled(false); setMessage("Setup motion locked. Drivers are disabled."); return; } if (!firmwareReady || !tokenRef.current || busy) return; if (!window.confirm("Enable bounded commissioning motion? Support gravity-loaded links, clear the selected joint path, and keep the physical E-stop in reach.")) return; setMotionEnablePending(true); servoQueueRef.current = ["J2"]; await send(`SERVO_CONFIG J1 ${tokenRef.current} ACTIVE_LOW INTERFACE_VERIFIED`); };
  const stopAll = async () => { homeQueueRef.current = []; servoQueueRef.current = []; clearHold(); setMotionEnabled(false); setMotionEnablePending(false); await send("STOP"); };
  const rawJog = async (direction: RawDirection) => { if (!motionEnabled || !rawDiscoveryReady || busy || homed[selectedJoint]) return; await send(`RAW_JOG ${selectedJoint} ${tokenRef.current} ${direction} DIRECTION_DISCOVERY_VERIFIED`); };
  const saveSetup = async () => { if (!firmwareReady || busy || motorHeld || !tokenRef.current) return; await send(`CAL_CONFIG ${selectedJoint} ${tokenRef.current} ${draft.homeRaw === "+" ? "HOME_RAW_POS" : "HOME_RAW_NEG"} ${draft.positiveRaw === "+" ? "POSITIVE_RAW_POS" : "POSITIVE_RAW_NEG"} ${draft.active} SAVE_CALIBRATION_VERIFIED`); };
  const homeJoint = async () => { if (!motionEnabled || !saved?.configured || busy || motorHeld || !tokenRef.current) return; await send(`HOME ${selectedJoint} ${tokenRef.current} START`); };
  const tapJog = async (direction: RawDirection) => { if (!motionEnabled || !saved?.configured || busy || (motorHeld && motorHeld !== selectedJoint) || !tokenRef.current) return; const amount = homed[selectedJoint] ? jogIncrement : Math.min(jogIncrement, 1000); await send(`JOG ${selectedJoint} ${tokenRef.current} ${direction} ${amount} GENTLE`); };
  const startHold = async (direction: RawDirection) => { if (!motionEnabled || !homed[selectedJoint] || moving || (motorHeld && motorHeld !== selectedJoint) || !tokenRef.current) return; await send(`HOLD ${selectedJoint} ${tokenRef.current} ${direction} ${holdSpeed} GENTLE`); };
  const stopHold = useCallback(async (holdPosition = true) => { const id = holdingRef.current; const releaseToken = tokenRef.current; if (!id) return; clearHold(); try { await sendRef.current(holdPosition ? `HOLD_RELEASE ${releaseToken} HOLD_POSITION_VERIFIED` : "STOP"); } catch { /* disconnected */ } }, [clearHold]);
  useEffect(() => { const stop = () => { if (holdingRef.current) void stopHold(false); }; const visibility = () => { if (document.hidden) stop(); }; window.addEventListener("blur", stop); document.addEventListener("visibilitychange", visibility); return () => { window.removeEventListener("blur", stop); document.removeEventListener("visibilitychange", visibility); }; }, [stopHold]);
  const releaseTorque = async () => { if (motorHeld === selectedJoint) await send(`MOTOR_HOLD ${selectedJoint} ${tokenRef.current} OFF HOLD_RELEASE_VERIFIED`); };
  const setLimit = async (kind: "MIN" | "MAX") => { if (!homed[selectedJoint] || busy || (motorHeld && motorHeld !== selectedJoint)) return; await send(`CAL_LIMIT ${selectedJoint} ${tokenRef.current} ${kind} CAPTURE_LIMIT_VERIFIED`); };
  const resetJoint = async () => { if (!saved?.configured || busy || motorHeld) return; if (!window.confirm(`Reset ${selectedJoint} directions and limits?`)) return; await send(`CAL_RESET ${selectedJoint} ${tokenRef.current} RESET_JOINT_CALIBRATION_VERIFIED`); };
  const homeAll = () => { if (!motionEnabled || !calibrationComplete || busy || motorHeld || !tokenRef.current) return; homeQueueRef.current = [...homeOrder]; sendNextHome(tokenRef.current); };

  const exportCalibration = () => { if (!header) return; const payload = { schema: "parol6.joint-calibration.v1", generated_at: new Date().toISOString(), complete: calibrationComplete, controller: { board: "BTT_OCTOPUS_PRO_V1_1_H723ZE", firmware, device_uid: header.deviceUid, flash_schema: header.schema, flash_sequence: header.sequence, storage: header.storage }, angle_model: { home_sensor_angle_deg: 0, source: "commanded_step_count_open_loop", warning: "Rehome after power-up, manual movement, missed steps, belt slip, or collision." }, joints: joints.map((item) => { const value = calibrations[item.id]; return { joint: item.id, name: item.name, motor_slot: item.slot, driver: item.driver, pulses_per_degree: value?.pulsesPerDegree || item.pulsesPerDegree, configured: value?.configured ?? false, home: value?.configured ? { angle_deg: 0, seek_motor_raw_direction: value.homeRaw, sensor_active_level: value.active } : null, directions: value?.configured ? { logical_positive_motor_raw_direction: value.positiveRaw, logical_negative_motor_raw_direction: value.negativeRaw } : null, soft_limits_deg: { minimum: value?.minSet ? value.minMdeg / 1000 : null, maximum: value?.maxSet ? value.maxMdeg / 1000 : null }, complete: Boolean(value?.configured && value.minSet && value.maxSet) }; }) }; const documentValue = { ...payload, checksum: { algorithm: "CRC32C", covers: "UTF-8 JSON.stringify(payload)", value: crc32c(JSON.stringify(payload)) } }; const url = URL.createObjectURL(new Blob([`${JSON.stringify(documentValue, null, 2)}\n`], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `PAROL6_joint_limits_${new Date().toISOString().replaceAll(":", "-")}.json`; anchor.click(); URL.revokeObjectURL(url); setMessage("Calibration JSON downloaded."); };

  const statusText = !connected ? "DISCONNECTED" : !firmwareReady ? "IDENTIFYING" : motionEnabled ? "SETUP MOTION ENABLED" : "CONNECTED · MOTION LOCKED";
  const negativeRaw = draft.positiveRaw === "+" ? "-" : "+"; const activeValue = draft.active === "ACTIVE_HIGH" ? 1 : 0; const sensorTriggered = sensor?.stable === activeValue;
  const jointStage = !saved?.configured ? 1 : !homed[selectedJoint] ? 2 : !(saved.minSet && saved.maxSet) ? 3 : 4;

  return <main className="simple-app">
    <header className="simple-header"><div><span className="simple-kicker">PAROL6 CALIBRATION · 0.8.1</span><h1>Set up one joint at a time.</h1><p>Test direction → save → home → set limits.</p></div><div className="simple-header-actions"><button className="simple-ghost" onClick={onShowWiring}>Wiring</button><button className="simple-stop" disabled={!connected} onClick={() => void stopAll()}>STOP</button><button className="simple-connect" onClick={connected ? () => void disconnect() : () => void connect()}>{connected ? "Disconnect" : "Connect USB"}</button></div></header>
    <section className={`simple-status ${motionEnabled ? "armed" : ""}`}><strong>{statusText}</strong><span>{message}</span><code>{firmware}</code></section>
    {!serialSupported && <div className="simple-warning">USB control needs current Chrome or Edge.</div>}
    {firmware === "0.8.0-calibration-rc" && <div className="simple-warning">Install firmware 0.8.1 to unlock raw direction testing before calibration.</div>}
    <section className="simple-controlbar"><div><span>MOTION</span><b>{motionEnabled ? "Ready" : "Locked"}</b><small>One confirmation enables this setup session. Firmware still bounds every move.</small></div><button className={motionEnabled ? "simple-lock" : "simple-enable"} disabled={!firmwareReady || busy} onClick={() => void enableMotion()}>{motionEnablePending ? "Preparing J1/J2…" : motionEnabled ? "Lock motion" : "Enable setup motion"}</button></section>
    <nav className="joint-tabs" aria-label="Select joint">{joints.map((item) => { const value = calibrations[item.id]; const done = value?.configured && value.minSet && value.maxSet; return <button key={item.id} className={`${selectedJoint === item.id ? "selected" : ""} ${done ? "done" : ""}`} onClick={() => setSelectedJoint(item.id)}><strong>{item.id}</strong><span>{item.name}</span><i>{done ? "DONE" : homed[item.id] ? "HOMED" : value?.configured ? "SAVED" : "SET UP"}</i></button>; })}</nav>

    <section className="joint-workbench">
      <div className="joint-workbench-head"><div><span>{joint.slot} · {joint.driver}</span><h2>{joint.id} — {joint.name}</h2></div><div className="live-readouts"><div><span>ANGLE</span><b>{(angleMdeg / 1000).toFixed(3)}°</b></div><div><span>HOME SENSOR</span><b className={sensorTriggered ? "triggered" : ""}>{sensor ? `${sensor.raw}/${sensor.stable ?? "—"}` : "—"}</b></div></div></div>
      <div className="stage-line">{["Direction", "Home", "Limits", "Done"].map((label, index) => <div key={label} className={jointStage > index + 1 ? "complete" : jointStage === index + 1 ? "current" : ""}><b>{index + 1}</b><span>{label}</span></div>)}</div>
      <div className="simple-step-grid">
        <article className={jointStage === 1 ? "focus" : ""}><div className="step-title"><b>1</b><div><h3>Find the directions</h3><p>Each test moves exactly 2° at half GENTLE speed.</p></div></div><div className="raw-test"><button disabled={!motionEnabled || !rawDiscoveryReady || busy || homed[selectedJoint]} onClick={() => void rawJog("-")}>Test raw −</button><button disabled={!motionEnabled || !rawDiscoveryReady || busy || homed[selectedJoint]} onClick={() => void rawJog("+")}>Test raw +</button></div><label>Which raw direction should mean joint +?<select value={draft.positiveRaw} onChange={(event) => setDrafts((current) => ({ ...current, [selectedJoint]: { ...draft, positiveRaw: event.target.value as RawDirection } }))}><option value="+">Raw +</option><option value="-">Raw −</option></select></label><div className="direction-result"><span>Joint + → raw {draft.positiveRaw}</span><span>Joint − → raw {negativeRaw}</span></div><label>Which raw direction moves toward home?<select value={draft.homeRaw} onChange={(event) => setDrafts((current) => ({ ...current, [selectedJoint]: { ...draft, homeRaw: event.target.value as RawDirection } }))}><option value="+">Raw +</option><option value="-">Raw −</option></select></label><label>Sensor value when triggered<select value={draft.active} onChange={(event) => setDrafts((current) => ({ ...current, [selectedJoint]: { ...draft, active: event.target.value as ActiveLevel } }))}><option value="ACTIVE_HIGH">1 · HIGH</option><option value="ACTIVE_LOW">0 · LOW</option></select></label><button className="primary-action" disabled={!firmwareReady || busy || !!motorHeld} onClick={() => void saveSetup()}>{saved?.configured ? "Save changes" : "Save joint setup"}</button></article>
        <article className={jointStage === 2 ? "focus" : ""}><div className="step-title"><b>2</b><div><h3>Home at 0°</h3><p>Seek up to 30°, back off, then latch slowly.</p></div></div><div className="home-state"><span>Sensor is</span><b className={sensorTriggered ? "triggered" : ""}>{sensorTriggered ? "TRIGGERED" : "CLEAR"}</b><small>Trigger level: {draft.active === "ACTIVE_HIGH" ? "1" : "0"}</small></div><button className="home-action" disabled={!motionEnabled || !saved?.configured || busy || !!motorHeld || (joint.servo && !servoGates[selectedJoint])} onClick={() => void homeJoint()}>{homed[selectedJoint] ? "Home again" : "Home joint"}</button><p className="step-note">If home is farther than 30°, use raw tests before saving or gentle tap jogs after saving to move closer.</p></article>
        <article className={jointStage === 3 ? "focus wide" : "wide"}><div className="step-title"><b>3</b><div><h3>Jog and capture limits</h3><p>Hold a direction for continuous motion. Release stops and holds position.</p></div></div><div className="jog-settings"><label>Tap distance<select value={jogIncrement} onChange={(event) => setJogIncrement(Number(event.target.value))}><option value="1000">1°</option><option value="5000">5°</option><option value="10000">10°</option></select></label><label>Hold speed <strong>{holdSpeed / 1000}°/s</strong><input type="range" min="3000" max="45000" step="1000" value={holdSpeed} onChange={(event) => setHoldSpeed(Number(event.target.value))} /></label></div><div className="jog-controls"><button disabled={!motionEnabled || !saved?.configured || busy || (motorHeld !== null && motorHeld !== selectedJoint)} onClick={() => void tapJog("-")}>− Tap</button><button className={holding === selectedJoint ? "moving" : ""} disabled={!motionEnabled || !homed[selectedJoint] || (moving && holding !== selectedJoint) || (motorHeld !== null && motorHeld !== selectedJoint)} onPointerDown={(event) => { if (event.button === 0) { event.currentTarget.setPointerCapture(event.pointerId); void startHold("-"); } }} onPointerUp={() => void stopHold(true)} onPointerCancel={() => void stopHold(false)} onLostPointerCapture={() => void stopHold(false)}>− Hold</button><button className={holding === selectedJoint ? "moving" : ""} disabled={!motionEnabled || !homed[selectedJoint] || (moving && holding !== selectedJoint) || (motorHeld !== null && motorHeld !== selectedJoint)} onPointerDown={(event) => { if (event.button === 0) { event.currentTarget.setPointerCapture(event.pointerId); void startHold("+"); } }} onPointerUp={() => void stopHold(true)} onPointerCancel={() => void stopHold(false)} onLostPointerCapture={() => void stopHold(false)}>+ Hold</button><button disabled={!motionEnabled || !saved?.configured || busy || (motorHeld !== null && motorHeld !== selectedJoint)} onClick={() => void tapJog("+")}>+ Tap</button></div>{motorHeld === selectedJoint && <button className="release-torque" onClick={() => void releaseTorque()}>Release holding torque</button>}<div className="limit-capture"><div><span>MINIMUM</span><b>{saved?.minSet ? `${(saved.minMdeg / 1000).toFixed(3)}°` : "Not set"}</b><button disabled={!homed[selectedJoint] || busy || (motorHeld !== null && motorHeld !== selectedJoint)} onClick={() => void setLimit("MIN")}>Set min here</button></div><div><span>CURRENT</span><b>{(angleMdeg / 1000).toFixed(3)}°</b><small>Home = 0.000°</small></div><div><span>MAXIMUM</span><b>{saved?.maxSet ? `${(saved.maxMdeg / 1000).toFixed(3)}°` : "Not set"}</b><button disabled={!homed[selectedJoint] || busy || (motorHeld !== null && motorHeld !== selectedJoint)} onClick={() => void setLimit("MAX")}>Set max here</button></div></div></article>
      </div>
      <div className="joint-footer"><span>{saved?.configured ? `Saved · sequence ${header?.sequence ?? "—"}` : "No saved setup"}</span><button disabled={!saved?.configured || busy || !!motorHeld} onClick={() => void resetJoint()}>Reset this joint</button></div>
    </section>

    <section className="finish-bar"><div><span>ROBOT CALIBRATION</span><h2>{completeCount} / 6 joints complete</h2><p>{allHomed ? "All joints currently homed." : "Finish each joint, then Home All and export JSON."}</p></div><div><button disabled={!header} onClick={exportCalibration}>Export JSON</button><button className="home-all" disabled={!motionEnabled || !calibrationComplete || busy || !!motorHeld} onClick={homeAll}>Home All</button></div></section>
    <details className="simple-log"><summary>Controller log</summary><pre>{logs.length ? logs.join("\n") : "Waiting for connection…"}</pre></details>
  </main>;
}
